[workspace]
authors = ["Vik <vpc726729@hotmail.com>"]
channels = ["conda-forge"]
name = "BeyondHumanCognitionXX"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.7,<3.15"
